# Copyright 2023 The Cross-Media Measurement Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'Create Infra'

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment to run the flow for.'
        options:
          - QA
          - NIGHTLY
      deploy_kingdom:
        required: true
        type: boolean
      deploy_duchy-1:
        required: true
        type: boolean
      deploy_duchy-2:
        required: true
        type: boolean
      deploy_duchy-3:
        required: true
        type: boolean

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: 'Halo CMM'
    runs-on: ubuntu-22.04

    steps:
      - name: Create Kingdom
        if: inputs.create_kingdom == true
        run: echo "Kingdom Created."
        shell: bash

      - name: Create Duchy - 1
        if: inputs.create_duchy-1 == true
        run: echo "Duchy-1 Created."
        shell: bash

      - name: Create Duchy - 2
        if: inputs.create_duchy-2 == true
        run: echo "Duchy-2 Created."
        shell: bash

      - name: Create Duchy - 3
        if: inputs.create_duchy-3 == true
        run: echo "Duchy-3 Created."
        shell: bash